apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-todo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-todo
  template:
    metadata:
      labels:
        app: go-todo
    spec:
      containers:
        - name: app
          # ðŸ‘‡ REMPLACE CECI PAR TON VRAI PSEUDO ET NOM DE REPO ðŸ‘‡
          image: ghcr.io/kaez/go-todo:latest
          ports:
            - containerPort: 8080 # Le port de ton code Go
