apiVersion: v1
kind: Service
metadata:
  name: go-todo-svc
  namespace: default
spec:
  selector:
    app: go-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-todo-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    # ðŸ‘‡ C'est l'URL que tu taperas dans ton navigateur
    - host: go-todo.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-todo-svc
                port:
                  number: 80
